### ISSUE TITLE
Route [logout] not defined when auth not configured

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/Laravel-CoreUI#13]
The readme suggests that make:coreui command is not required. But, after installing the plugin, the template throws ErrorException:
`Route [logout] not defined. (View: /home/vagrant/code/dnha/vendor/hz-hbo-ict/laravel-core-ui/resources/views/master.blade.php) (View: /home/vagrant/code/dnha/vendor/hz-hbo-ict/laravel-core-ui/resources/views/master.blade.php)`

**Comment by Lucky-Loek** [comment]
Fixed in https://github.com/HZ-HBO-ICT/Laravel-CoreUI/commit/207929327fc79b4aabb348e2f61a08adff8bf414, update to 1.0.4 to receive the fix.
