### ISSUE TITLE
Adding breadcrumbs support

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/Laravel-CoreUI#22]
Relates to #11. Add a wiki page or some other method to explain how to install and use the Laravel Breadcrumbs package in combination with this package

**Comment by Lucky-Loek** [comment]
Hmm, I don't like to introduce dependencies that aren't absolutely necessary. The [Laravel Breadcrumbs](https://github.com/davejamesmiller/laravel-breadcrumbs) package has great documentation in my opinion. 

We could think of a way to introduce breadcrumbs without editing the views, for example like so:

    @section('breadcrumbs', Breadcrumbs::render('verkiezing.show', $election))

And then letting it default to the page name.

**Comment by dwaard** [comment]
Exactly my thoughts. And also a wiki page/blog post on how to set up and use it in applications that use this pacakge. This doesn't create direct dependencies
