### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by Lucky-Loek** [HZ-HBO-ICT/Laravel-CoreUI#8]
Template is currently hardcoded in English, let's make it possible to support multiple languages.

- [x] Configure everything translatable with `{{ __() }}` function (i.e. login and register screens, etc)
- [x] Create Dutch i18n file
- [x] Update `make:coreui` command to publish translations too

https://laravel.com/docs/5.7/localization

**Comment by dwaard** [comment]
publishing translations method is 'heavily inspired' from JeroenNoten. See the readme
